@startuml classDiagram

class AuthUser {
    String first_name
    String last_name
    String password
    String email
    String googleId
}

class Merchant {
    int id
    String owner
    String store_name
    Point location
    String cuisineType
    double distance
    int totalSeats
    int freeSeats
    double occupancyRate
}

class Prenotation {
    int id
    int owner
    int merchant
    int amount
    DateTime date
    bool isExpired
    bool isValid
    DateTime dateOfCreation
}

AuthUser "1" -> "many" Prenotation: Prenotatore
Prenotation "many" <- "1" Merchant: Prenotazione
Merchant "1" <- "1" AuthUser: Proprietario
@enduml