@startuml classDiagram

class AuthUser {
    String first_name
    String last_name
    String password
    String email
    String googleId
    boolean isMerchant
}

class Merchant {
    int id
    String owner
    String store_name
    Point location
    String cuisineType
    double distance
    int totalSeats
    int freeSeats
    double occupancyRate
}

class Prenotation {
    int id
    int owner
    int merchant
    int amount
    DateTime date
    bool isExpired
    bool isValid
    DateTime dateOfCreation
}

class Menu{
    int id
    int merchantId
    List<MenuItem> menuItems
}

class MenuItem{
    int id
    String name
    double price
    MenuSection section
}

enum MenuSection{
    Primo
    Secondo
    Dolce
    Contorno
}

Merchant "1" -> "1" Menu
Menu "1" -> "many" MenuItem: Elemento del menu
MenuItem "1" -> "1" MenuSection

AuthUser "1" -> "many" Prenotation
Prenotation "many" <- "1" Merchant: Prenotazione
Merchant "many" <- "1" AuthUser: Proprietario
@enduml