@startuml Prenotazione

hide footbox

actor User as user
participant Auth_Service as authservice
participant Prenotation_Service as prenotationservice
participant Merchant_Service as merchantservice
participant User_Service as userservice

user -> authservice: Richiesta di prenotazione
authservice -> prenotationservice: Richiesta di prenotazione
prenotationservice -> prenotationservice: Controlla se ci sono posti disponibili
alt Se ci sono posti disponibili
prenotationservice -> prenotationservice: Segna la prenotazione
prenotationservice -> merchantservice: Aggiorna il dato ridondato
prenotationservice -> userservice: Aggiunge la prenotazione attuale
prenotationservice -> authservice: Prenotazione effettuata
authservice -> user: Prenotazione effettuata
else Se non ci sono posti disponibili
prenotationservice -> authservice: Prenotazione impossibile
authservice -x user: Prenotazione impossibile
end 

@enduml